# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(313, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 311, 81))
        self.groupBox.setObjectName("groupBox")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(10, 30, 281, 31))
        self.comboBox.setObjectName("comboBox")
        self.btnStartscan = QtWidgets.QToolButton(self.centralwidget)
        self.btnStartscan.setGeometry(QtCore.QRect(100, 400, 91, 41))
        self.btnStartscan.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.btnStartscan.setCheckable(False)
        self.btnStartscan.setObjectName("btnStartscan")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 80, 311, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.btnBuW = QtWidgets.QToolButton(self.groupBox_2)
        self.btnBuW.setGeometry(QtCore.QRect(50, 30, 41, 41))
        self.btnBuW.setStatusTip("")
        self.btnBuW.setText("lineart")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":images/blackuwhite.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":images/blackuwhite_activ.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnBuW.setIcon(icon)
        self.btnBuW.setIconSize(QtCore.QSize(48, 48))
        self.btnBuW.setCheckable(True)
        self.btnBuW.setAutoExclusive(True)
        self.btnBuW.setObjectName("btnBuW")
        self.btnGray = QtWidgets.QToolButton(self.groupBox_2)
        self.btnGray.setGeometry(QtCore.QRect(130, 30, 41, 41))
        self.btnGray.setText("gray")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":images/grey.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":images/grey_activ.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnGray.setIcon(icon1)
        self.btnGray.setIconSize(QtCore.QSize(48, 48))
        self.btnGray.setCheckable(True)
        self.btnGray.setAutoExclusive(True)
        self.btnGray.setObjectName("btnGray")
        self.btnColor = QtWidgets.QToolButton(self.groupBox_2)
        self.btnColor.setGeometry(QtCore.QRect(220, 30, 41, 41))
        self.btnColor.setText("color")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":images/color.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":images/color_activ.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnColor.setIcon(icon2)
        self.btnColor.setIconSize(QtCore.QSize(48, 48))
        self.btnColor.setCheckable(True)
        self.btnColor.setChecked(True)
        self.btnColor.setAutoExclusive(True)
        self.btnColor.setObjectName("btnColor")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 300, 131, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.resolutions = QtWidgets.QComboBox(self.groupBox_3)
        self.resolutions.setGeometry(QtCore.QRect(10, 40, 111, 26))
        self.resolutions.setStyleSheet("padding-left:3")
        self.resolutions.setCurrentText("")
        self.resolutions.setModelColumn(0)
        self.resolutions.setObjectName("resolutions")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 160, 311, 131))
        self.groupBox_4.setObjectName("groupBox_4")
        self.scanpath = QtWidgets.QLineEdit(self.groupBox_4)
        self.scanpath.setGeometry(QtCore.QRect(10, 40, 221, 26))
        self.scanpath.setText("")
        self.scanpath.setClearButtonEnabled(True)
        self.scanpath.setObjectName("scanpath")
        self.btnOpenDir = QtWidgets.QToolButton(self.groupBox_4)
        self.btnOpenDir.setGeometry(QtCore.QRect(250, 30, 41, 41))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":images/folder-pictures.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":images/folder-pictures.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnOpenDir.setIcon(icon3)
        self.btnOpenDir.setIconSize(QtCore.QSize(32, 32))
        self.btnOpenDir.setObjectName("btnOpenDir")
        self.filename = QtWidgets.QLineEdit(self.groupBox_4)
        self.filename.setGeometry(QtCore.QRect(10, 90, 221, 26))
        self.filename.setObjectName("filename")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 340, 58, 18))
        self.label.setObjectName("label")
        self.statusLed = QtWidgets.QLabel(self.centralwidget)
        self.statusLed.setGeometry(QtCore.QRect(260, 330, 41, 41))
        self.statusLed.setText("")
        self.statusLed.setPixmap(QtGui.QPixmap(":images/led_red.png"))
        self.statusLed.setScaledContents(True)
        self.statusLed.setObjectName("statusLed")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 313, 23))
        self.menubar.setObjectName("menubar")
        self.menuCalibrate = QtWidgets.QMenu(self.menubar)
        self.menuCalibrate.setObjectName("menuCalibrate")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionScanFolder = QtWidgets.QAction(MainWindow)
        self.actionScanFolder.setObjectName("actionScanFolder")
        self.actionCalibrate = QtWidgets.QAction(MainWindow)
        self.actionCalibrate.setObjectName("actionCalibrate")
        self.menuCalibrate.addAction(self.actionCalibrate)
        self.menubar.addAction(self.menuCalibrate.menuAction())

        self.retranslateUi(MainWindow)
        self.resolutions.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Scanner"))
        self.btnStartscan.setText(_translate("MainWindow", "Start Service"))
        self.groupBox_2.setTitle(_translate("MainWindow", "ScanMode"))
        self.btnBuW.setToolTip(_translate("MainWindow", "Black&White scan", "Black&White Line Mode"))
        self.btnGray.setToolTip(_translate("MainWindow", "Gray scan"))
        self.btnColor.setToolTip(_translate("MainWindow", "Color scan"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Resolution"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Scan Path"))
        self.scanpath.setPlaceholderText(_translate("MainWindow", "Path to Scanned Images"))
        self.btnOpenDir.setText(_translate("MainWindow", "..."))
        self.filename.setPlaceholderText(_translate("MainWindow", "Enter file name"))
        self.label.setText(_translate("MainWindow", "Status"))
        self.menuCalibrate.setTitle(_translate("MainWindow", "Config"))
        self.actionScanFolder.setText(_translate("MainWindow", "ScanFolder"))
        self.actionCalibrate.setText(_translate("MainWindow", "Calibrate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
s
